apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: ots-app
spec:  
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017    
  selector:
    name: mongodb-pod
    app: ots-app
        