apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: ots-app
spec:  
  ports:
    - port: 4000
      targetPort: 4000      
  selector:
    name: gateway-app-pod
    app: ots-app
        