apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ots-ingress
spec:
  rules:
    - host: otsdashboard.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
                service:
                  name: dashboard-service
                  port: 
                    number: 80
                  
             
           