apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    name: mongodb-deployment
    app: ots-app
    
spec:
  selector:
    matchLabels:
      name: mongodb-pod
      app: ots-app
  replicas: 1
  template:
    metadata:
      name: mongodb-pod
      labels:
        name: mongodb-pod
        app: ots-app
    spec:
      containers:
        - name: mongodb
          image: mongo            
          ports:
          - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password